'use server';

/**
 * @fileOverview This file contains the Genkit flow for generating a professional summary based on user-provided information.
 *
 * @exports generateProfessionalSummary - A function that generates a professional summary.
 * @exports ProfessionalSummaryInput - The input type for the generateProfessionalSummary function.
 * @exports ProfessionalSummaryOutput - The output type for the generateProfessionalSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ProfessionalSummaryInputSchema = z.object({
  name: z.string().describe('The name of the user.'),
  experienceYears: z.number().describe('The number of years of experience.'),
  jobTitle: z.string().describe('The current or desired job title.'),
  skills: z.string().describe('A comma-separated list of skills.'),
});
export type ProfessionalSummaryInput = z.infer<typeof ProfessionalSummaryInputSchema>;

const ProfessionalSummaryOutputSchema = z.object({
  summary: z.string().describe('A professional summary generated by the AI.'),
});
export type ProfessionalSummaryOutput = z.infer<typeof ProfessionalSummaryOutputSchema>;

export async function generateProfessionalSummary(
  input: ProfessionalSummaryInput
): Promise<ProfessionalSummaryOutput> {
  return generateProfessionalSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'professionalSummaryPrompt',
  input: {schema: ProfessionalSummaryInputSchema},
  output: {schema: ProfessionalSummaryOutputSchema},
  prompt: `Write a 3-line professional summary for {{name}}, a {{jobTitle}} with {{experienceYears}} years of experience. The skills are: {{skills}}.`,
});

const generateProfessionalSummaryFlow = ai.defineFlow(
  {
    name: 'generateProfessionalSummaryFlow',
    inputSchema: ProfessionalSummaryInputSchema,
    outputSchema: ProfessionalSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
